import { renderToStaticMarkup } from "react-dom/server";
import type { GitHubActivity } from "~/utils/github-activity.server";
import type { PublicMonitorSummary } from "~/utils/public-monitor";
import { scorePublicSlo } from "~/utils/monitor-slo";

export type EngineeringCardData = { generatedAt: number; monitor: Pick<PublicMonitorSummary, "asOfMs" | "windows"> | null; activity: GitHubActivity | null };
type Colors = { bg: string; panel: string; panelAlt: string; border: string; text: string; muted: string; accent: string; good: string; warning: string };

const L = { width: 900, height: 668, gutter: 38, metricY: 174, metricHeight: 82, stageY: 270, stageHeight: 132, signalsY: 455, signalsHeight: 151 } as const;
const STAGE_LABELS: Record<string, string> = { fetch_data_ns: "Market data", attach_raw_close_ns: "Preparation", indicators_ns: "Indicators", generate_signals_ns: "Signals", process_other_ns: "Guardrails" };

function durationNs(value: number | null | undefined) { if (value == null || !Number.isFinite(value)) return "—"; const ms = value / 1e6; return ms < 1 ? `${(ms * 1_000).toFixed(0)} µs` : `${ms.toFixed(ms < 100 ? 1 : 0)} ms`; }
function percent(value: number | null | undefined) { return value == null || !Number.isFinite(value) ? "—" : `${(value * 100).toFixed(value >= .995 ? 1 : 0)}%`; }

function Panel({ x, y, width, height, colors, alt = false }: { x: number; y: number; width: number; height: number; colors: Colors; alt?: boolean }) { return <rect x={x} y={y} width={width} height={height} rx="10" fill={alt ? colors.panelAlt : colors.panel} stroke={alt ? colors.border : undefined} />; }
function SectionLabel({ y, children, colors }: { y: number; children: React.ReactNode; colors: Colors }) { return <text x={L.gutter} y={y} fill={colors.muted} fontSize="11" letterSpacing="1.5">{children}</text>; }
function MetricCard({ x, width, title, value, detail, children, colors }: { x: number; width: number; title: string; value: string; detail: string; children?: React.ReactNode; colors: Colors }) { return <g><Panel x={x} y={L.metricY} width={width} height={L.metricHeight} colors={colors} /><text x={x + 18} y="198" fill={colors.muted} fontSize="10" fontWeight="700">{title}</text><text x={x + 18} y="225" fill={colors.text} fontSize="17" fontWeight="700">{value}</text>{children}<text x={x + 18} y="250" fill={colors.muted} fontSize="10">{detail}</text></g>; }

function StageChart({ stages, colors }: { stages: PublicMonitorSummary["windows"]["day"]["stages"]; colors: Colors }) {
	const entries = Object.entries(stages).filter(([, metric]) => metric.p99Ns != null).slice(0, 5);
	if (!entries.length) return <text x="56" y="354" fill={colors.muted} fontSize="11">No stage samples published in the seven-day window.</text>;
	const largest = Math.max(...entries.map(([, metric]) => metric.p99Ns ?? 0), 1);
	return <>{entries.map(([stage, metric], index) => { const value = metric.p99Ns ?? 0; const y = 334 + index * 13; return <g key={stage}><text x="56" y={y} fill={colors.muted} fontSize="10">{STAGE_LABELS[stage] ?? stage}</text><rect x="202" y={y - 7} width="490" height="6" rx="3" fill={colors.border} /><rect x="202" y={y - 7} width={Math.max(4, Math.round(value / largest * 490))} height="6" rx="3" fill={colors.accent} /><text x="712" y={y} fill={colors.text} fontSize="10" fontWeight="700">{durationNs(value)}</text></g>; })}</>;
}

function ActivityChart({ values, colors }: { values: number[]; colors: Colors }) { const largest = Math.max(...values, 1); return <g>{values.map((value, index) => { const height = Math.max(3, Math.round(value / largest * 28)); return <rect key={index} x={728 + index * 31} y={588 - height} width="16" height={height} rx="3" fill={colors.accent} opacity={value ? 1 : .28} />; })}<line x1="716" y1="588" x2="860" y2="588" stroke={colors.border} /><text x="716" y="601" fill={colors.muted} fontSize="9">W-3</text><text x="801" y="601" fill={colors.muted} fontSize="9">THIS WK</text></g>; }

function EngineeringCardSvg({ data, theme }: { data: EngineeringCardData; theme: "dark" | "light" }) {
	const colors: Colors = theme === "dark" ? { bg: "#09090b", panel: "#18181b", panelAlt: "#111113", border: "#27272a", text: "#fafafa", muted: "#a1a1aa", accent: "#60a5fa", good: "#34d399", warning: "#fbbf24" } : { bg: "#ffffff", panel: "#f4f4f5", panelAlt: "#fafafa", border: "#e4e4e7", text: "#18181b", muted: "#71717a", accent: "#2563eb", good: "#059669", warning: "#d97706" };
	const week = data.monitor?.windows.week ?? null, reference = week?.processing?.p99Ns != null ? week : null;
	const sloScore = scorePublicSlo(week), sloColor = sloScore.observed === 0 ? colors.muted : sloScore.passing === sloScore.observed ? colors.good : colors.warning;
	const latency = durationNs(reference?.processing?.p99Ns), latencyWidth = reference?.processing?.p99Ns != null ? Math.max(40, Math.min(112, 220 - Math.log10(reference.processing.p99Ns / 1e3) * 31)) : 0, parityWidth = Math.max(0, Math.min(154, (week?.shadowMatchRate ?? 0) * 154));
	const timestamp = new Intl.DateTimeFormat("en-US", { hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false, timeZoneName: "short" }).format(data.generatedAt);
	return <svg xmlns="http://www.w3.org/2000/svg" width={L.width} height={L.height} viewBox={`0 0 ${L.width} ${L.height}`} role="img" aria-labelledby="title desc"><title id="title">Lohit Aryan engineering portfolio</title><desc id="desc">Public engineering portfolio and live system diagnostic, generated {timestamp}</desc><rect width={L.width} height={L.height} rx="18" fill={colors.bg} /><rect x="1" y="1" width="898" height="666" rx="17" fill="none" stroke={colors.border} /><g fontFamily="ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace">
		<text x="38" y="47" fill={colors.text} fontSize="22" fontWeight="700">LOHIT ARYAN</text><text x="38" y="71" fill={colors.muted} fontSize="11" letterSpacing="2">ENGINEERING PORTFOLIO</text><circle cx="767" cy="42" r="6" fill={colors.good} /><text x="862" y="47" fill={colors.text} fontSize="12" fontWeight="700" textAnchor="end">PUBLIC CARD</text><text x="38" y="105" fill={colors.muted} fontSize="11">REFRESHED {timestamp}</text><line x1="38" y1="125" x2="862" y2="125" stroke={colors.border} />
		<SectionLabel y={157} colors={colors}>PUBLIC MONITOR · LAST 7 DAYS</SectionLabel>
		<MetricCard x={38} width={264} title="END-TO-END LATENCY" value={`p50 ${durationNs(week?.processing?.p50Ns)}`} detail={`p99 ${durationNs(week?.processing?.p99Ns)} · event → decision`} colors={colors} /><MetricCard x={316} width={264} title="SHADOW PARITY" value={percent(week?.shadowMatchRate)} detail={`coverage ${percent(week?.barCoverageRate)}`} colors={colors}><rect x="334" y="232" width="228" height="4" rx="2" fill={colors.border} /><rect x="334" y="232" width={parityWidth * (228 / 154)} height="4" rx="2" fill={colors.good} /></MetricCard><MetricCard x={594} width={268} title="FRESHNESS & QUEUE" value={durationNs(week?.freshness.p99Ns)} detail={`feed p99 · queue ${durationNs(week?.queueLag.p99Ns)}`} colors={colors} />
		<Panel x={38} y={L.stageY} width={824} height={L.stageHeight} colors={colors} alt /><text x="56" y="298" fill={colors.text} fontSize="12" fontWeight="700">STAGE TAIL LATENCY</text><text x="56" y="314" fill={colors.muted} fontSize="10">7-day p99 by critical-path stage · bars are relative and not additive</text><StageChart stages={week?.stages ?? {}} colors={colors} />
		<SectionLabel y={438} colors={colors}>ENGINEERING SIGNALS</SectionLabel><Panel x={38} y={L.signalsY} width={510} height={L.signalsHeight} colors={colors} alt /><text x="56" y="483" fill={colors.muted} fontSize="10" fontWeight="700" letterSpacing="1.2">PUBLIC SYSTEM DIAGNOSTIC</text><line x1="224" y1="498" x2="224" y2="584" stroke={colors.border} /><line x1="378" y1="498" x2="378" y2="584" stroke={colors.border} />
		<text x="56" y="516" fill={sloColor} fontSize="18" fontWeight="700">{sloScore.passing}/{sloScore.total}</text><text x="56" y="540" fill={colors.muted} fontSize="10">SLO checks passing</text><text x="56" y="558" fill={colors.muted} fontSize="10">{sloScore.observed}/{sloScore.total} checks observed</text>
		{reference ? <><text x="242" y="516" fill={colors.text} fontSize="13" fontWeight="700">p99 {latency}</text><text x="242" y="540" fill={colors.muted} fontSize="10">7D REFERENCE</text><text x="242" y="558" fill={colors.muted} fontSize="10">event → decision</text><rect x="242" y="573" width="112" height="5" rx="2.5" fill={colors.border} /><rect x="242" y="573" width={latencyWidth} height="5" rx="2.5" fill={colors.accent} /></> : <><text x="242" y="516" fill={colors.text} fontSize="12" fontWeight="700">No latency</text><text x="242" y="540" fill={colors.muted} fontSize="10">samples published</text></>}{reference ? <><text x="396" y="516" fill={colors.text} fontSize="13" fontWeight="700">{reference.eventCount.toLocaleString()}</text><text x="396" y="540" fill={colors.muted} fontSize="10">events observed</text><text x="396" y="558" fill={colors.muted} fontSize="10">7-day aggregate</text></> : <><text x="396" y="516" fill={colors.text} fontSize="12" fontWeight="700">No events</text><text x="396" y="540" fill={colors.muted} fontSize="10">in reference</text></>}
		<Panel x={564} y={L.signalsY} width={298} height={L.signalsHeight} colors={colors} alt /><text x="582" y="483" fill={colors.muted} fontSize="10" fontWeight="700" letterSpacing="1.2">PUBLIC REPOSITORY ACTIVITY</text>{data.activity ? <><text x="582" y="520" fill={colors.text} fontSize="24" fontWeight="700">{data.activity.commitsLast7Days}</text><text x="582" y="540" fill={colors.muted} fontSize="10">COMMITS · LAST 7 DAYS</text><text x="582" y="572" fill={colors.text} fontSize="13" fontWeight="700">{data.activity.commitsLast28Days}</text><text x="582" y="590" fill={colors.muted} fontSize="10">commits · last 28 days</text><ActivityChart values={data.activity.weeklyCommits} colors={colors} /></> : <><text x="582" y="520" fill={colors.text} fontSize="13" fontWeight="700">Activity unavailable</text><text x="582" y="540" fill={colors.muted} fontSize="10">Public commit history</text><text x="582" y="558" fill={colors.muted} fontSize="10">could not be read</text></>}
		<line x1="38" y1="630" x2="862" y2="630" stroke={colors.border} /><text x="38" y="650" fill={colors.muted} fontSize="10">BACKEND · ML · CLOUD · PRODUCT SYSTEMS</text><text x="862" y="650" fill={colors.accent} fontSize="10" textAnchor="end">LOHITARYAN.DEV</text>
	</g></svg>;
}

export function renderEngineeringCard(data: EngineeringCardData, theme: "dark" | "light" = "dark") { return renderToStaticMarkup(<EngineeringCardSvg data={data} theme={theme} />); }
